# Generated by Django 5.2.8 on 2025-12-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='archivo',
            field=models.ImageField(upload_to='', verbose_name='Fotografía'),
        ),
    ]
