# Generated by Django 5.2.8 on 2025-12-04 19:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_foto_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='archivo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
    ]
